query GetVentilation($houseAddress: String!) {
  getVentilation(house_address: $houseAddress) {
    id
    house_municipality
    house_address
    house_type
    house_build_year
    house_square
    house_floors
    house_entrances
    house_flats
    house_chimneys_count
    house_chimneys_length
    house_chimneys_cap_size
    house_chimneys_has_valve
    house_ventilation_channels_count
    house_ventilation_channels_length
    house_ventilation_channels_dimensions
    house_has_cojoined_chimneys_ventilation
    house_has_flue
    house_20c_form_date
    house_20c_form_conclusion
    house_gas_shutdown_date
    house_gas_shutdown_affected_flats_count
    house_gas_shutdown_resume_date
    house_gas_shutdown_resume_affected_flats_count
    house_management_organization_name
    house_management_community_name
    house_management_direct_management
    checkup_chimneys_contractor_name
    checkup_chimneys_contractor_contract_number
    checkup_chimneys_contractor_contract_date
    checkup_chimneys_attestation_date
    checkup_chimneys_attestation_contract_number
    checkup_chimneys_attestation_image_available
    checkup_ventilation_contractor_name
    checkup_ventilation_contractor_contract_number
    checkup_ventilation_contractor_contract_date
    checkup_ventilation_attestation_date
    checkup_ventilation_attestation_contract_number
    checkup_ventilation_attestation_image_available
    inspection_chimneys_contractor_contract_number
    inspection_chimneys_contractor_contract_date
    inspection_chimneys_contractor_name
    inspection_chimneys_maintenance_required_count
    inspection_chimneys_overhaul_required_count
    inspection_chimneys_reconstruction_required_count
    inspection_chimneys_construction_required_count
    inspection_ventilation_contractor_contract_number
    inspection_ventilation_contractor_contract_date
    inspection_ventilation_contractor_name
    inspection_ventilation_maintenance_required_count
    inspection_ventilation_overhaul_required_count
    inspection_ventilation_reconstruction_required_count
    inspection_ventilation_construction_required_count
    cost_estimating_chimneys_maintenance_cost
    cost_estimating_chimneys_overhaul_cost
    cost_estimating_chimneys_reconstruction_cost
    cost_estimating_chimneys_construction_cost
    cost_estimating_chimneys_contract_info
    cost_estimating_ventilation_maintenance_cost
    cost_estimating_ventilation_overhaul_cost
    cost_estimating_ventilation_reconstruction_cost
    cost_estimating_ventilation_construction_cost
    cost_estimating_ventilation_contract_info
    repairs_chimneys_maintenance_repaired_count
    repairs_chimneys_maintenance_period
    repairs_chimneys_maintenance_contract_info
    repairs_chimneys_maintenance_cost
    repairs_chimneys_overhaul_repaired_count
    repairs_chimneys_overhaul_period
    repairs_chimneys_overhaul_contract_info
    repairs_chimneys_overhaul_cost
    repairs_chimneys_reconstruction_repaired_count
    repairs_chimneys_reconstruction_period
    repairs_chimneys_reconstruction_contract_info
    repairs_chimneys_reconstruction_cost
    repairs_chimneys_construction_repaired_count
    repairs_chimneys_construction_period
    repairs_chimneys_construction_contract_info
    repairs_chimneys_construction_cost
    repairs_ventilation_maintenance_repaired_count
    repairs_ventilation_maintenance_period
    repairs_ventilation_maintenance_contract_info
    repairs_ventilation_maintenance_cost
    repairs_ventilation_overhaul_repaired_count
    repairs_ventilation_overhaul_period
    repairs_ventilation_overhaul_contract_info
    repairs_ventilation_overhaul_cost
    repairs_ventilation_reconstruction_repaired_count
    repairs_ventilation_reconstruction_period
    repairs_ventilation_reconstruction_contract_info
    repairs_ventilation_reconstruction_cost
    repairs_ventilation_construction_repaired_count
    repairs_ventilation_construction_period
    repairs_ventilation_construction_contract_info
    repairs_ventilation_construction_cost
    note
    house_fias_guid
    house_address_normalized
  }
}
